# Generated by Django 5.0.6 on 2026-06-25 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('Numerical', 'Numerical'), ('Linguistic', 'Linguistic'), ('Structural', 'Structural'), ('Thematic', 'Thematic'), ('Other', 'Other')], default='Other', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=True)),
                ('vote_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveryVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'Up'), (-1, 'Down')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discovery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='community.discovery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='discovery',
            index=models.Index(fields=['is_public', '-vote_score'], name='community_d_is_publ_49794a_idx'),
        ),
        migrations.AddIndex(
            model_name='discovery',
            index=models.Index(fields=['is_public', '-created_at'], name='community_d_is_publ_c743a8_idx'),
        ),
        migrations.AddIndex(
            model_name='discovery',
            index=models.Index(fields=['category'], name='community_d_categor_d878a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='discoveryvote',
            unique_together={('user', 'discovery')},
        ),
    ]
