# Generated by Django 5.0.6 on 2026-06-27 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_surah', models.IntegerField(blank=True, null=True)),
                ('last_verse', models.IntegerField(blank=True, null=True)),
                ('progress', models.JSONField(blank=True, default=dict)),
                ('streak_count', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_read_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
