# Generated by Django 5.0.6 on 2026-06-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_readingstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingstate',
            name='daily_goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readingstate',
            name='today_ayahs',
            field=models.IntegerField(default=0),
        ),
    ]
