# Generated by Django 5.0.6 on 2026-06-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_readingstate_daily_goal_readingstate_today_ayahs'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingstate',
            name='reading_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
