# Generated by Django 5.0.6 on 2026-06-25 03:54

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quran', '0002_wordroot_root_display'),
    ]

    operations = [
        # Enable the pgvector extension before any VectorField/HnswIndex is used.
        VectorExtension(),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField(unique=True)),
                ('label', models.CharField(max_length=200)),
                ('keywords', models.JSONField(default=list)),
                ('size', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-size'],
            },
        ),
        migrations.CreateModel(
            name='VerseEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('theme_cluster', models.IntegerField(blank=True, null=True)),
                ('model_name', models.CharField(max_length=120)),
                ('computed_at', models.DateTimeField()),
                ('verse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='quran.verse')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='verseemb_hnsw_cos', opclasses=['vector_cosine_ops']), models.Index(fields=['theme_cluster'], name='semantic_ve_theme_c_f65c4d_idx')],
            },
        ),
    ]
