# Generated by Django 5.0.6 on 2026-06-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordroot',
            name='root_display',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
