# Generated by Django 5.0.6 on 2026-06-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_wordroot_root_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordroot',
            name='meaning_en',
            field=models.TextField(blank=True),
        ),
    ]
