# Generated by Django 5.0.6 on 2026-06-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0003_alter_wordroot_meaning_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='TafsirEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_key', models.CharField(db_index=True, max_length=12)),
                ('language', models.CharField(choices=[('en', 'English'), ('id', 'Indonesian')], max_length=5)),
                ('resource_name', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(blank=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tafsir entries',
            },
        ),
        migrations.AddConstraint(
            model_name='tafsirentry',
            constraint=models.UniqueConstraint(fields=('verse_key', 'language'), name='uniq_tafsir_per_verse_lang'),
        ),
    ]
