# Generated by Django 5.0.6 on 2026-07-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0004_tafsirentry_tafsirentry_uniq_tafsir_per_verse_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='hizb_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verse',
            name='manzil_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verse',
            name='rub_el_hizb_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verse',
            name='ruku_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verse',
            name='sajdah_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='verse',
            index=models.Index(fields=['ruku_number'], name='quran_verse_ruku_nu_bb8a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='verse',
            index=models.Index(fields=['hizb_number'], name='quran_verse_hizb_nu_d139c4_idx'),
        ),
    ]
