# Generated by Django 5.0.6 on 2026-07-10 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0005_verse_hizb_number_verse_manzil_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('arabic', models.CharField(max_length=100)),
                ('segment_type', models.CharField(choices=[('prefix', 'prefix'), ('stem', 'stem'), ('suffix', 'suffix')], max_length=6)),
                ('pos_tag', models.CharField(blank=True, max_length=4)),
                ('pos_detail', models.CharField(blank=True, max_length=16)),
                ('lemma', models.CharField(blank=True, max_length=100)),
                ('verb_form', models.CharField(blank=True, max_length=4)),
                ('mood', models.CharField(blank=True, max_length=8)),
                ('voice', models.CharField(blank=True, max_length=4)),
                ('features', models.CharField(blank=True, max_length=200)),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments', to='quran.wordroot')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='quran.word')),
            ],
            options={
                'ordering': ['word', 'position'],
                'indexes': [models.Index(fields=['pos_detail'], name='quran_words_pos_det_d594fc_idx'), models.Index(fields=['verb_form'], name='quran_words_verb_fo_7d2bcc_idx'), models.Index(fields=['mood'], name='quran_words_mood_516bfb_idx'), models.Index(fields=['voice'], name='quran_words_voice_699308_idx')],
                'unique_together': {('word', 'position')},
            },
        ),
    ]
